print('parth777'.isalnum())   
print('sudarshanlondhe'.isalpha())   
print('777f'.isdigit())   
print('sdsdsdsd'.islower())   
print(''.islower())   
print('SUDARSHANl'.isupper())   
print('My Name Is Parth'.istitle())   
print(''.istitle())   
print(' '.isspace())   
print("Sudarshan".startswith("Su"))  
print("Hello".endswith("ello"))

print("parth".find("r"))
print("parth".index("r"))
print("parth".count("a"))
